### ISSUE TITLE
cuDNN failed to initialize

### ISSUE THREAD

**Issue by MeetGandhiMagna** [google-research/ravens#13]
This is the error that I am getting when trying to run train.py:
E tensorflow/stream_executor/cuda/cuda_dnn.cc:328] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR

After googling the error, I tried restarting my PC as well as other steps mentioned; however none helped.

**Comment by DanielTakeshi** [comment]
@MeetGandhiMagna  Can you provide the complete installation steps you performed? Thanks.

**Comment by MeetGandhiMagna** [comment]
The issue  has been resolved after updating Ubuntu.
